### ISSUE TITLE
Delete Ingress (service and co.)

### ISSUE THREAD

**Issue by mgvazquez** [appscode/voyager#1043] opened 2018-05-11 20:44 UTC
After create an Ingress by error, I don't have any way to delete it.
If I delete the Service (Ingress created by error), the Voyager Controller will recreate it again.

Is it a bug or I'm doing it wrong? I searched in the docs, but could't find a clue.

My Voyager version is 6.0.0

PD: Sorry for my bad English.

**Comment by tamalsaha** [comment] 2018-05-11 22:12
Find the ingress you created and delete that.

```
kubectl get ingress.voyager.appscode.com --all-namespaces
kubectl delete ingress.voyager.appscode.com -n <namespace> <ing-anme>
```

**Comment by tamalsaha** [comment] 2018-05-11 23:33
Fixed, as confirmed on slack. Closing.

**Closed by tamalsaha** 2018-05-11 23:33 UTC

**Comment by nanthan** [comment] 2018-09-15 13:38
I try to delete ingress name `test-ingress`

```
$kubectl get ingress.voyager.appscode.com --all-namespaces
NAMESPACE   NAME           AGE
default     test-ingress   1h
$kubectl delete ingress.voyager.appscode.com test-ingress
ingress.voyager.appscode.com "test-ingress" deleted
```
but the last command didn't return exit (stuck on message `ingress.voyager.appscode.com "test-ingress" deleted`) I need to cancel by ctrl+c

and when I get ingress agian, the ingress that I deleted showing up agian

**Comment by qiangli** [comment] 2018-12-09 01:59
as of today Dec 8, 2018, this issue seems still not fixed.

**Comment by bfalese-navent** [comment] 2018-12-19 12:53
Same problem here, can not delete a voyager ingress, keeps respawning.

**Comment by tamalsaha** [comment] 2018-12-19 13:11
@qiangli , @bfalese-navent , do you have any bad ingress that is throwing error? The OP had a badly formatted json as Ingress which broker the Voyager controller. You should be able to identify this from the voyager operator logs? You can talk to me via our slack channel https://slack.appscode.com/

**Comment by thorro** [comment] 2019-01-15 09:52
It got stuck on delete here, too, because of bad config given, no help even with `--grace-period=0 --force`.

I then did a replace on `ingress.voyager.appscode.com` object and it got replaced succesfully, then it deleted instantly.

**Comment by dperetti** [comment] 2019-02-02 14:17
Voyager v.8, same issue, can't get rid of the ingress from the example. Anything I try to delete is recreated. Ended up uninstalling voyager, and now I'm still having this a `ingress.voyager.appscode.com/test-ingress` that is still there after a force deletion !?
