### ISSUE TITLE
Problem with TCP Ingress on GKE

### ISSUE THREAD

**Issue by desertraider93** [appscode/voyager#1084] opened 2018-05-30 14:15 UTC
The problem is the following: I was trying to use a Minecraft server with the Voyager TCP load-balancer. This worked quite fine in the past but as today it’s not working anymore. I think it’s since I updated the GKE Cluster to the newest version but I'm not entirely sure about this. Here are my cluster infos:

![cluster](https://user-images.githubusercontent.com/1020759/40724152-a9636d44-6420-11e8-9ab6-90f187699766.PNG)

The problem I have encountered is that a normal Load Balancer would work. So it’s cant be the server which stopped working.
Here is the Service:

![serviceminecraft](https://user-images.githubusercontent.com/1020759/40724251-eb2d4b0a-6420-11e8-86fb-c323454cde96.PNG)

If I set “ClusterIP” to “LoadBalancer” and letting the "normal" GCE Load-Balancer do it's Job there is no problem with joining the server. But if I set it to ClusterIP and let voyager do the job its not working. The Minecraft deployments container has port 25565 configured.

Here is the Ingress:
![ingress](https://user-images.githubusercontent.com/1020759/40724351-263aed92-6421-11e8-9efd-dc5dc6054c0f.PNG)
And thats the service view:
![serviceview](https://user-images.githubusercontent.com/1020759/40724439-5d501c94-6421-11e8-9bc5-c34c25b45082.PNG)
If I'm now using the IP which I blacked out in the last image the server seems to establish a connection of some sort but it's timing out. It's like the server can't answer the user. But I'm not sure about this either. The problem is that this setup should have worked quite some time ago while it's now not working anymore. 

I'm thankful for every help I can get. If you need additional logs or screenshots or info please don't hesitate to ask.

**Comment by desertraider93** [comment] 2018-05-31 18:23
Hey, thanks for yesterday. I've tried to replace the LoadBalancer but unfortunately it's still isn't working. I tried today to made an additional rule with a HTTP port. The HTTP Port is working as intended. 
As small summary what works:
The HTTP Rule is working. I can browse my own wiki behind the "bluespice-service" without problems. But the connection to the minecraft server is timing out only if I using voyager. If I use the built in GKE Load-Balancer and replace "ClusterIP" with "Load-Balancer" it works. Here again the Ingress. Thanks in advance.
```
API Version:  voyager.appscode.com/v1beta1
Kind:         Ingress
Metadata:
  Cluster Name:
  Creation Timestamp:  2018-05-31T13:59:07Z
  Finalizers:
    voyager.appscode.com
  Generation:        1
  Resource Version:  5862964
  Self Link:         /apis/voyager.appscode.com/v1beta1/namespaces/default/ingresses/server-ingress
  UID:               c902c393-64da-11e8-a490-42010a840014
Spec:
  Resources:
  Rules:
    Host:  wiki.test.de
    Http:
      Node Port:  0
      Paths:
        Backend:
          Service Name:  bluespice-service
          Service Port:  80
        Path:            /wiki
      Port:              0
    Host:                ogzv8wicl5crvajfz5ettte7fgw2.test.com
    Tcp:
      Backend:
        Service Name:  ogzv8wicl5crvajfz5ettte7fgw2-minecraft-minecraft
        Service Port:  25565
      Node Port:       0
      Port:            22807
```

**Comment by desertraider93** [comment] 2018-06-01 01:02
I have found something. I've created two complete new clusters in GKE. One with Version 1.9.6-gke.1 and one with 1.10.2-gke.3. 
While the first version is running without issues. The newest version of GKE doesn't seem to run. To replicate the steps im posting my commands which I used one after another to set up both clusters:

```
kubectl create serviceaccount tiller --namespace kube-system
kubectl apply -f helm-rbac.yaml
helm init --service-account tiller
helm install --name minetest stable/minecraft
helm upgrade minetest --set minecraftServer.eula=true,persistence.dataDir.enabled=false stable/minecraft
curl -fsSL -o onessl https://github.com/kubepack/onessl/releases/download/0.3.0/onessl-linux-amd64   && chmod +x onessl   && sudo mv onessl /usr/local/bin/
helm install appscode/voyager --name voyager-operator --version 7.0.0   --set cloudProvider=gke   --set apiserver.ca="$(onessl get kube-ca)"   --set apiserver.enableValidatingWebhook=true
kubectl apply -f test-lb3.yaml

```
The helm-rbac.yaml:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: kube-system

```
test-lb3.yaml:
```
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.appscode.com/type: LoadBalancer
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"voyager.appscode.com/v1beta1","kind":"Ingress","metadata":{"annotations":{"ingress.appscode.com/type":"LoadBalancer","kubernetes.io/ingress.class":"voyager"},"name":"server-ingress","namespace":"default"},"spec":{"rules":[{"host":"wiki.test.de","http":{"paths":[{"backend":{"serviceName":"bluespice-service","servicePort":80},"path":"/wiki"}]}},{"host":"ogzv8wicl5crvajfz5ettte7fgw2.test.com","tcp":{"backend":{"serviceName":"ogzv8wicl5crvajfz5ettte7fgw2-minecraft-minecraft","servicePort":25565},"port":22807}}]}}
    kubernetes.io/ingress.class: voyager
  clusterName: ""
  creationTimestamp: 2018-05-31T13:59:07Z
  finalizers:
  - voyager.appscode.com
  generation: 1
  name: server-ingress
  namespace: default
  resourceVersion: "5927573"
  selfLink: /apis/voyager.appscode.com/v1beta1/namespaces/default/ingresses/server-ingress
  uid: c902c393-64da-11e8-a490-42010a840014
spec:
  resources: {}
  rules:
  - host: ogzv8wicl5crvajfz5ettte7fgw2.test.com
    tcp:
      backend:
        serviceName: minetest-minecraft
        servicePort: 25565
      nodePort: 0
      port: 22507
```
After that I only changed the "minetest-minecraft" service from LoadBalancer to ClusterIP.
This seems really odd... Is it even possible that an GKE update could have done something like this?

**Comment by tamalsaha** [comment] 2018-06-01 01:15
I have to manually check and get back to you.

**Comment by tamalsaha** [comment] 2018-06-01 14:51
I just tried with 1.10.2-gke.3 and experienced similar issue. I saw that HAProxy pod itself wold not respond to curl commands. Trying to debug further.

**Comment by tamalsaha** [comment] 2018-06-01 15:52
Here are the steps for reproducing this problem:

```
# 1. Create a 1 node 1.10-gke.3 GKE cluster from web console using cos image.

# 2. Give you cluster-admin permission kubectl create clusterrolebinding cluster-admin-binding --clusterrole=cluster-admin --user=your-email
 
# 3. Deploy voyager: 
curl -fsSL https://raw.githubusercontent.com/appscode/voyager/7.0.0/hack/deploy/voyager.sh \
    | bash -s -- --provider=gke

# 4. run nginx
kubectl run nginx --image=nginx
kubectl expose deployment nginx --name=web --port=4567 --target-port=80

# 5. create ingress

apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  namespace: default
spec:
  rules:
  - host: 'web.example.com'
    tcp:
      port: '4567'
      backend:
        serviceName: web
        servicePort: 4567

# 6. Find external-ip of voyager-test-ingress
$ kubectl get svc
NAME                   TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)          AGE
kubernetes             ClusterIP      10.59.240.1     <none>          443/TCP          13m
voyager-test-ingress   LoadBalancer   10.59.247.66    35.232.80.106   4567:30683/TCP   6m
web                    ClusterIP      10.59.243.128   <none>          4567/TCP         10m

# 7
curl -vv https://<external-ip of voyager-test-ingress>:4567

```

**Comment by tamalsaha** [comment] 2018-06-01 16:03
@desertraider93 , #gke channel on official kube slack is telling me that it is some kernel bug. 

https://kubernetes.slack.com/archives/C09R1TL6A/p1527868371000173

![gke-kernel-bug](https://user-images.githubusercontent.com/94814/40850854-8d6c20f8-657a-11e8-8e5d-b67f9fbae533.png)

**Comment by tamalsaha** [comment] 2018-06-03 15:32
Closing since nothing to do from Voyager's side.

**Closed by tamalsaha** 2018-06-03 15:32 UTC
